image: python:3.9.1

pipelines:
  default:
    - step:
        caches:
          - pip
        script: 
          - apt-get update && apt-get install -y libgraphviz-dev graphviz 
          - pip install tox 
          - python setup.py install
          - tox -e tests 
          - tox -e docs 
          - # twine upload --repository-url https://test.pypi.org/legacy/ -u ${TEST_PYPI_USERNAME}  -p  ${TEST_PYPI_PASS} dist/*
